### ISSUE TITLE
Note: count vs. nunique

### ISSUE THREAD

**Issue by Caealana** [SLaguerta/biodiversity-capstone#1]
https://github.com/SLaguerta/biodiversity-capstone/blob/3900ecc447454d02b41d1fd722b43aee76d7dc61/biodiversity.py#L123

count will count all scientific names that show up for each category of endangerment. However, some of the scientific names are repeated in the data, so you should use nunique so that you only count the unique species for each category.
Refer to the following picture to see how the results from using count and nunique differ:
<img width="859" alt="countvsnuniqueconservationstatus" src="https://user-images.githubusercontent.com/14001120/36921873-4f9b4f9a-1e3c-11e8-8b3e-6186b32c6cad.png">

**Comment by SLaguerta** [comment]
Commit ae71ece refers to the change in the .ipynb file; the .py file is also updated in Commit f386957
