### ISSUE TITLE
Summary: Meets Expectations

### ISSUE THREAD

**Issue by Caealana** [SLaguerta/biodiversity-capstone#5]
Overall, this was a great project! 

 All of your python code worked correctly towards accomplishing the various data science tasks. You followed many of the best conventions concerning indentation and variable naming conventions. This helped in making your python code easily readable. There were some areas where your code could have been simplified and made more efficient, but these are little details that are honed as you gain more experience coding.

 I would suggest you practice adding in your own comments and a README to this github repository to give some context to your code. Comments answer questions like 'What were you thinking when you writing this code?' and 'What is the purpose of this chunk of code? Are there currently any issues with it?" [Here ](https://guides.github.com/features/wikis/) is a helpful guide for creating READMEs that give a good introduction to your project.

On your presentation:
<img width="915" alt="screenshot at mar 03 12-24-20" src="https://user-images.githubusercontent.com/14001120/36936600-d1049b80-1edd-11e8-9dde-1c70b02087c5.png">

You give great details about your project process here. I would suggest using some text color changes or bolding to highlight important details and make your slide look less like one monotonous blob of text. For example, you can bold your three categories in this slide. You may not need to include all of the details of all of your data transformations. I think it may be more audience-friendly to simply mention that species that are considered not protected are from the "No Intervention" group and species that are considered protected belong to one of the other groups that are not "No Intervention". Explaining your definitions in terms of True and False can be confusing for some audience members who don't have experience with boolean logic.

<img width="782" alt="screenshot at mar 03 12-27-20" src="https://user-images.githubusercontent.com/14001120/36936631-40b919b0-1ede-11e8-8656-4a3468b02754.png">

I was impressed with your presentation of your chi-square test results! You did a great job of including all of the relevant information in forms that are easily digestible. It is easy to read and understand your results.

**Comment by SLaguerta** [comment]
Thank you for your comments, @Caealana! I really appreciated it. I made a few commits today to resolve the issue regarding count() vs nunique(), as well as other improvements in code you recommended. I also made a few edits to the presentation and added the readme.md file. Thanks again.
